# Site settings
title: Konkr.io
email: mike@konkr.io
description: >
  Konkr is a free turn-based strategy game that runs in your browser.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.konkr.io"
twitter_username: Konkr_io
github_username:  embair
linkedin_url: "https://www.linkedin.com/in/michal-bures"

# Build settings
markdown: kramdown
highlighter: true