# Site settings
title: Konkr.io
email: konkr.io@gmail.com
description: >
  Konkr is a deceptively simple yet ruthlessly punishing turn based strategy strategy game that runs in your web browser.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://konkr.io"
twitter_username: Konkr_io
github_username:  embair

# Build settings
markdown: kramdown
highlighter: true