# Site settings
title: Konkr.io
email: mike@konkr.io
description: >
  Konkr is a free turn-based strategy game that runs in your browser.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://konkr.io"
twitter_username: Konkr_io
github_username:  embair

# Build settings
markdown: kramdown
highlighter: true