# Site settings
title: Konkr.io
email: dev@konkr.io
description: >
  Konkr is a free turn-based strategy game that runs in you browser. Expand your kingdom, build up your economy, crush your enemies, then crush your allies too!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.konkr.io"
twitter_username: konkr_dev
github_username:  michal-bures
discord_link: https://discord.com/invite/C9HucB9arH

linkedin_url: "https://www.linkedin.com/in/michal-bures"
excerpt_separator: <!-- excerpt-end -->

# Build settings
markdown: kramdown
highlighter: true


defaults:
  -
    scope:
      path:            "releases/**/*"
    values:
      sitemap:         false
