[[redirects]]
  from = "/v2/dev/*"
  to = "/"
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://www.itch.io http://localhost"
    Service-Worker-Allowed = "/"
