[[redirects]]
  from = "/v2/dev/*"
  to = "/"
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://embair.itch.io/konkr http://localhost:63342"
    Service-Worker-Allowed = "/"
