export type HelpPageKey =
    | 'tutorial-goal'
    | 'tutorial-economy'
    | 'tutorial-units'
    | 'tutorial-combat'
    | 'tutorial-rivals'
    | 'tutorial-bandits'
    | 'tutorial-rebellion'
    | 'tutorial-summary'
    | 'tutorial-rewind'
